//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabDetail
    {
        public int LabId { get; set; }
        public string LabName { get; set; }
        public string LabOwnerName { get; set; }
        public string Email { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public byte[] Add3 { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> State { get; set; }
        public string About { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual State State1 { get; set; }
        public virtual TestLabPrice TestLabPrice { get; set; }
    }
}
