//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Cities = new HashSet<City>();
            this.LabDetails = new HashSet<LabDetail>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<LabDetail> LabDetails { get; set; }
    }
}
