//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.TestLabPrices = new HashSet<TestLabPrice>();
        }
    
        public int C__ { get; set; }
        public string TestName { get; set; }
        public string TestDesc { get; set; }
    
        public virtual ICollection<TestLabPrice> TestLabPrices { get; set; }
    }
}
