//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTest
    {
        public int BookTestId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TestLabId { get; set; }
    }
}
