//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabDataBaseEntities : DbContext
    {
        public LabDataBaseEntities()
            : base("name=LabDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<LabDetail> LabDetails { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestLabPrice> TestLabPrices { get; set; }
        public virtual DbSet<BookTest> BookTests { get; set; }
    }
}
